previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    plan: starter
    previewPlan: starter
    name: showcase-backend-monorepo
    region: oregon
    env: node
    buildCommand: cd showcase-backend && yarn && yarn run prisma:generate && yarn run build
    startCommand: cd showcase-backend && yarn prisma:ci && yarn start
    afterFirstDeployCommand: cd showcase-backend && yarn prisma:seed
    envVars:
      - fromGroup: showcase-backend
      - key: DATABASE_URL
        fromDatabase:
          name: showcase-monorepo
          property: connectionString
databases:
  - name: showcase-monorepo
    plan: starter
    previewPlan: starter
    region: oregon
