previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    plan: starter
    previewPlan: starter
    name: showcase-backend-monorepo
    region: frankfurt
    env: node
    buildCommand: node scripts/git-info.js && cd showcase-backend && yarn && yarn run build:app
    startCommand: cd showcase-backend && yarn run migration:run && yarn start
    afterFirstDeployCommand: cd showcase-backend && yarn run seed:run
    envVars:
      - fromGroup: showcase-backend
      - key: DATABASE_URL
        fromDatabase:
          name: showcase-monorepo
          property: connectionString
databases:
  - name: showcase-monorepo
    plan: starter
    previewPlan: starter
    region: frankfurt
