-- AlterTable
ALTER TABLE "Badge" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "BadgeType" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Cause" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
