
export const SPEND_LIMIT_DEFAULT = 1000
export const SPEND_LIMIT_KYC_VERIFIED = SPEND_LIMIT_DEFAULT * 10

export const BADGE_TYPE_MIN_SALE_PRICE = 0.01
export const BADGE_TYPE_MAX_SALE_PRICE = 200
export const BADGE_TYPE_MIN_SUPPLY = 1
export const BADGE_TYPE_MAX_SUPPLY = 1000000
export const BADGE_TYPE_MAX_TITLE_LENGTH = 20
export const BADGE_TYPE_MAX_DESC_LENGTH = 240

export const DONATION_MIN_AMOUNT = 0.05
export const DONATION_MAX_AMOUNT = 0.5



