name: Expo Release Candidate
on:
  push:
    branches:
      - rc
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: mydea/action-wait-for-api@v1
        with:
          url: 'https://showcase-monorepo-pagl.onrender.com/__healthy'
          expected-response-field: 'status'
          expected-response-field-value: 'ok'
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Install Dependencies
        working-directory: ./showcase-mobile
        run: |
          yarn install
          yarn generate
          expo publish --release-channel=release-candidate
        env:
          DEV_API: 'https://showcase-monorepo-pagl.onrender.com/graphql'

      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.io/@myshowcase/ShowcaseApp?release-channel=release-candidate).
